doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Company:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Company/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Company\Domain\Model'
                alias: Company
            CreditRequest:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/CreditRequest/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\CreditRequest\Domain\Model'
                alias: CreditRequest

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
