parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Company/Domain/Model/'
            - '../src/CreditRequest/Domain/Model/'
            - '../src/Kernel.php'

    # Repository interface → implementation bindings
    App\Company\Domain\Repository\CompanyRepositoryInterface:
        alias: App\Company\Infrastructure\Persistence\Repository\DoctrineCompanyRepository
